### ISSUE TITLE
Hu Tao passive applied (even when she is below the lvl)

### ISSUE THREAD

**Issue by Mars4it** [frzyc/genshin-optimizer#1003]
When trying to do some playing around with my Hu Tao (who's only 60/60) I noticed her damage was higher than what I got in game. Turns out that her Ascension 4 Passive "Sanguine Rouge" was somehow active despite her not being at that ascension level yet.
![Screenshot 2023-02-19 1 22 05 PM](https://user-images.githubusercontent.com/125372615/219967676-c46ea2ad-7dce-4d56-8096-d06809e715ae.png)

**Comment by StainAE86** [comment]
This is because you've levelled her up to 70 or higher within GO, turned her A4 conditional on, then dropped her level back down to 60 without turning it off first.

It's a known issue across all characters with conditional passives but an extremely low priority thing to fix because you can't drop your character level in-game. Once you have access to ascension passives in-game you can never lose that.

**Comment by nguyentvan7** [comment]
Well I try to fix this/prevent this. I can/should add an extra check

**Comment by Mars4it** [comment]
> This is because you've levelled her up to 70 or higher within GO, turned her A4 conditional on, then dropped her level back down to 60 without turning it off first.
> 
> It's a known issue across all characters with conditional passives but an extremely low priority thing to fix because you can't drop your character level in-game. Once you have access to ascension passives in-game you can never lose that.

yooo thanks mate sorry I messed it up lol
