### ISSUE TITLE
Flower of paradise lost effect wont apply

### ISSUE THREAD

**Issue by GunnerCat** [frzyc/genshin-optimizer#1015]
i tried to optimize my artifact for kuki which uses FOPL, but the problem is that what ever i do in the setting, the optimizer just refuses to use the FOPL set.

currently i am using a FOPL set which has higher hyperbloom damage compared to all possible combination of my artifact (across all set)
![image](https://user-images.githubusercontent.com/35151526/220645636-3133779b-0561-44bc-afd2-1e4132a8b1a1.png)

idk if there is anything i missed, or it is a mistake, but would be glad if i have an answer for it, thank you.

**Comment by D1firehail** [comment]
Have you enabled the set effect for FOPL?

**Comment by nguyentvan7** [comment]
Since your optimized build is losing damage, sounds like your set effects are on. Other things it could be:

* You disabled fopl 4p in set config
* You disabled one of the main stats you were using for fopl
* You limited artifact level which is now excluding one of the fopl pieces
* One or many of the fopl pieces are excluded in the optimizer

**Comment by StainAE86** [comment]
Upload your database for further assistance (can just rename the .json to .txt and GitHub will accept it as an attachment)

**Comment by nguyentvan7** [comment]
Closing due to staleness. Let us know if you are still facing this isssue
