### ISSUE TITLE
Allow artifacts 2p/4p sets to be disabled directly from the build results 

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1151]
Implement the final idea: https://github.com/frzyc/genshin-optimizer/issues/1151#issuecomment-1518389725

**Origional Issue:** This should be default behaviour only if "all" artifacts are allowed on that character. However if you have a character with a custom list (eg; vv or bs character for example) you now have to disable the 2p and 4p of the new sets.

It would be nice for new sets to be off by default if the artifact set config is not in the default "all on" state.

![image](https://user-images.githubusercontent.com/101696552/233740429-c038f0b9-5fb2-43d7-82bd-0a586103a3fe.png)
![image](https://user-images.githubusercontent.com/101696552/233740462-93c2846d-6578-4b40-b208-405f5ab9d2cb.png)

**Comment by nguyentvan7** [comment]
Pretty sure this used to be the other way around and we changed it to current behavior due to requests. Its the same as the character allow list, where we will always add new characters to your custom list. if it shows up, then just disable it and reoptimize. 

The alternative is more harmful because people might not even realize new sets are disabled

**Comment by StainAE86** [comment]
Another option, easy access to disable 2p/4p directly from the build results:

![image](https://user-images.githubusercontent.com/101696552/233743457-bff483ad-8940-41b5-bf69-3da2dfca4222.png)
