### ISSUE TITLE
Add multi-character multi-optimization

### ISSUE THREAD

**Issue by BreadCatOW** [frzyc/genshin-optimizer#1167]
Basically, let users specify a team, add damage instances from each individual character, then optimize the artifacts of all characters at the same time given this scenario.

**Comment by nguyentvan7** [comment]
The primary issue with this is computation time/math. Right now, we have 5 variables to build a single character (each artifact). Even with just 2 characters, we jump to 10 variables, and this scales exponentially with the number of artifacts. Not exactly n^5 or n^10, but somewhere around there (where n = number of artifacts). The time to calculate this would be obscene, basically.

For example, assuming 50 artifacts per slot, for a single character we get `50^5` = 312,500,000 builds, which is very reasonable even without pruning.  
For 2 characters we get `(50^5)*(49^5)` = 88,273,515,312,500,000 builds. Obviously there is a lot of pruning and extra math that we could do, but the initial search space is still huge.  
For 4 character we get `(50^5)*(49^5)*(48^5)*(47^5)` = 5,158,529,261,270,896,983,736,320,000,000,000 builds
(I hope my math isn't too wrong or toofless or lantua will smite me)

Otherwise, it is difficult to add this as well because the user will need to ensure all 4 characters are using multi-optimizations that are all over the same rotation/timescale. Not impossible, but could very easily lead to users misusing the system by accident

**Comment by GriAle** [comment]
Good afternoon.
You are right, if you count the whole group at once, then yes the complexity increases exponentially. 

But it is not necessary to do so.
We can create a group, prescribe the order of calculations in this group and which parameter we are optimizing. When miscalculating the first character in the group, we equip artifacts obtained as a result of the calculation (only it is necessary to somehow mark which artifacts were changed as a result of this calculation) and move on to the next character in the optimization group.

This will not increase the complexity, only increase the duration.

**Comment by nguyentvan7** [comment]
See #439 for more on why we won't add serial character optimization like that
