### ISSUE TITLE
Create a custom Dialog override to prevent overlay race condition

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#1497]
Similar to #967, we need to modify Dialog to use Popper instead of Popover or something similar. The backdrop is getting stuck on certain race conditions which renders the whole site unusable.

Probably related to https://github.com/mui/material-ui/issues/32286

**Comment by nguyentvan7** [comment]
I can recreate the stuck state 100% of the time by opening the KQMS dialog in TC tab, and rapidly double clicking the "Use KQMS" button

**Comment by nguyentvan7** [comment]
Seems related to the fact that the callback passed to KQMS is recalculated when you press the button. Other buttons do not exhibit this behavior, and adding long-running functions to the button other than the one passed in also does not exhibit this behavior

**Comment by nguyentvan7** [comment]
I actually don't need to double click at all to cause the issue. it does seem to happen a lot more frequently on the dev server for whatever reason

**Comment by adch99** [comment]
I can reproduce this bug pretty much every time with the following:
- Firefox 123.0.1 (64-bit) on Arch Linux

Steps to Reproduce:
- Navigate to Teams tab
- Add a TC Build to a character from the Loadouts popup
- Click the KQMS icon and click Use KQMS

Expected Behaviour:
- The KQM standard should be applied to the minimum rolls per substat

Actual Behaviour:
- The page becomes unresponsive though the sliders have been moved
- After reloading the page, the standard has been applied and can be used normally
- Even if the sliders are changed again and the KQMS button is clicked again, these subsequent clicks will not cause the bug in my testing

I am unsure of what exact logs or details are needed to fix this issue. Please let me know if any more details are needed.

**Comment by nguyentvan7** [comment]
Bumping to fix ASAP because it happens almost every time you use the kqm dialog
