### ISSUE TITLE
Add a toggle to disable using artifacts in teammates' active builds when optimizing

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#1548]
Add a toggle to the optimize tab in team, to disallow using artifacts that are in teammates' builds.

**Comment by HassnHamada** [comment]
I'm working on this issue.

I'll also look into the problem causing negative numbers to appear in "Artifact Configuration" since they are probably in the same module/directory.
<img width="570" alt="Screenshot 2024-03-01 at 11 50 25 AM" src="https://github.com/frzyc/genshin-optimizer/assets/44922829/4fc3954c-6e10-4f6c-95bc-2bb91f6a376b">

**Comment by frzyc** [comment]
Sounds good, let me know if you hit any blockers, this is definitely more complicated logic than tasks you've worked on before.
