### ISSUE TITLE
Creating a new character from the Character page should create a new Team

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#1693]
Similar to our migration process. There is a bit of lack of feedback when creating a new character, and leaves the user in limbo

**Comment by frzyc** [comment]
Creating the character opens the character editor, that allows users to create a team, which then opens up the Team settings UI. 
I don't think it makes sense to automatically create a team+loadout, since the user have no chance to name the team/loadout, and when they go to the team, it doesnt open the team setting, which is a worse workflow.
