### ISSUE TITLE
It is possible to delete a weapon used within a build (active or not)

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1774]
Loadout Settings:
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/6d29fe59-4993-4e12-81db-d169bfa5e2ae)

Overview Tab: (lowercase "polearm" too)
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/3bf8bdea-68bd-480d-8a52-238028940756)

Optimize Tab:
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/fd3a506b-dba0-4285-af88-b3f0feb5e0c7)

Optimize Result: (no error explaining why no builds are returned due to a missing weapon)
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/5ce5bd0b-c7e8-4094-b14b-a966d7e2ee37)

If you edit the build via the "Loadout Settings" it will automatically force a dull blade, regardless of which weapon type the character is:
![image](https://github.com/frzyc/genshin-optimizer/assets/101696552/a3d7a74d-0825-4286-ad55-efa83639acf8)

**Comment by StainAE86** [comment]
I would just like to point out that the action of deleting a weapon is even more destructive than deleting a team.

Surely the solution won't be to remove the delete button from the weapon cards?

**Comment by frzyc** [comment]
It's an engine limitation to always have a weapon. (which is why in the case where a weapon is deleted a lot of stuff like optimization won't work). The intention is that if you delete a weapon that is in a build a "valid" weapon has to replace it, which is a dull blade. sounds like additional work is needed to ensure this weird state won't occur.
