### ISSUE TITLE
"Lock" function for Teams, Characters, Loadouts and Builds

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#1782]
Much like GO has adopted the "Lock" functionality for Artifacts and Weapons from Genshin itself that prevents a user accidentally deleting an Artifact or Weapon.

Why not introduce this same functionality to all aspects of GO? This could potentially allow the addition of a Delete button directly on Character and Team cards because we're also providing the option to prevent against destructive deletion in a means that should not require any explanation to the user as both GO and Genshin already utilize this exact UI.

**Comment by frzyc** [comment]
The lock data from artifacts and weapons are data we can scan using scanners, however, loadouts and teams do not exist in game. So the data source is different, since user have to intentionally generate data, wheras art/weapon lock state is a data from in-game they can leverage. 
The major benefit of the "lock" feature, in both genshin and GO, seem to be protection from "mass removal". However, since loadout and teams have more nuanced data, there are no mass removal, nor do i intend for that to exist in the future. Lastly, for a user to know whether a team/loadout is worth locking, they'd be in the detail UI anyways, which is next to where the delete button, so I am not sure what this request will do other than just add more clutter to the exist UI.
