### ISSUE TITLE
[Feature Suggestion] Opt-Out of GO Ads

### ISSUE THREAD

**Issue by ScorelessPine** [frzyc/genshin-optimizer#2078]
I can't say I understand the decision for adding these self-referential ad spaces to the website, and to be honest, they're just as intrusive as normal ads, if not moreso. On a wider display, these GO ad spaces even push the entire content of the page to one side.
Screenshots shown below on an Ultrawide display.

Artifact Page with ads: 
![image](https://github.com/frzyc/genshin-optimizer/assets/28274052/ee338dd8-cafc-4c3b-89d8-3f6e9f153bd5)

vs

Artifact Page with GO Ads: ![image](https://github.com/frzyc/genshin-optimizer/assets/28274052/697000b1-6d43-4677-bc10-4413e43945b6)

Main Page with ads: 
![image](https://github.com/frzyc/genshin-optimizer/assets/28274052/65147c03-bc2a-4b43-b6b8-d3a7ad985168)

vs

Main Page with GO Ads:
![image](https://github.com/frzyc/genshin-optimizer/assets/28274052/1174b2b4-2900-4d33-a73f-be59a45b2bed)

I understand it's easy to click the X to make it disappear for the page until a reload, but it doesn't stay gone, and these pseudo-ad spaces are just as annoying as real advertisements.

**Comment by frzyc** [comment]
Looks like the main problem here is the size of the side banner ads filling up the full width. Since GO Ads are intended to simulate the ad space here, its width here should be capped. 

Regarding the initial request, I have decided against implementing an opt-out feature for ads at this time. Instead, the sole measure to be taken will be the reduction of the prominently sized side banner advertisements as a mitigation strategy. (https://github.com/frzyc/genshin-optimizer/pull/2079)

**Comment by ScorelessPine** [comment]
Can't say I agree with the decision but that's obviously not up to me. The statement still stands that these ad simulations are just as intrusive as normal ad spaces.

**Comment by nguyentvan7** [comment]
I'm gonna assume that's the point

Also, most ad blockers will still offer a way to block these specific ones :eyes:
