### ISSUE TITLE
Add a "character editor" to TC Build editor

### ISSUE THREAD

**Issue by frzyc** [frzyc/genshin-optimizer#2154]
Likely will fulfill https://github.com/frzyc/genshin-optimizer/issues/2144
For people who theorycraft different builds under different conditions, it makes sense to assume a specific character level/talent/constellation. 

Workbreakdown:
- Add character data to TC builds
- Add Character editor to TC editor/overview
- Add additional logic for useTeamData for overriding the character data from buildTC
- Add comparable fields (level/talent/constellation) to show on build results when comparing two builds with different character data
- Likely have to account for comparing results of nodes that may or may not show in comparable builds (like nodes hidden behind constellation)
- Add character data to TC builds when converting build to TC builds

**Comment by nguyentvan7** [comment]
Is it in scope to include this for real builds too?

my use case is determining if a constellation or weapon is 'worth' to pull. Weapons are covered since you can save multiple builds.

Constellation editing in TC builds is nice (and good for team sharing), but doesn't cover me wanting to optimize with my own artifacts to compare.

I understand its a lot of work to add it in general, so just checking

**Comment by frzyc** [comment]
No, adding this to real builds will potentially break the "plug and play" versatility of loadouts,(and subsequently team exim) I am not sure if I want to cover the usecase of "is something worth" in terms of a "real build" workflow officially, I think being able to address it and compare in TC build is probably good enough for most cases. and we can maintain the "real builds are real" assumption going forward.
