### ISSUE TITLE
Duplicated `<strong>` in char_$char.json

### ISSUE THREAD

**Issue by LeafyLuigi** [frzyc/genshin-optimizer#2221]
Most, if not all char\_*$char*.json files located in `libs/gi/dm-localization/assets/locales/$lang/char_$char.json` have a duplicated `<strong>` on their 10th lines (for "Normal Attack" subheadings) leading to slightly strange HTML generation with a nested `<strong>` on the teams > (team id) > ($char) > talents page.

&nbsp;

### Expected result:

HTML tree to contain something along the lines of 
```html
<strong>Normal Attack</strong>
```

### Actual result:

HTML tree contains
```html
<strong><strong>Normal Attack</strong></strong>
```

**Comment by HassnHamada** [comment]
I can do this using find and replace. But I think it may be risky. Is there a better way to do it?

**Comment by frzyc** [comment]
find and replace likely won't work, since the next time we generate pipeline it will have to be done again. the "correct" way to fix this issue is to fix the datamine parsing pipeline: https://github.com/frzyc/genshin-optimizer/blob/master/libs/gi/dm-localization/src/executors/gen-locale/executor.ts
