### ISSUE TITLE
Add Weapon conditional and Artifact 4-set conditional into the build preview

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#310]
So these two:
![image](https://user-images.githubusercontent.com/101696552/164953469-bbb3ce7e-f52e-4dd1-a273-83b4de856253.png)
![image](https://user-images.githubusercontent.com/101696552/164953465-a826ab96-f7e9-489a-867a-e700cc9308e8.png)

Appear in here:
![image](https://user-images.githubusercontent.com/101696552/164953501-78853a12-fbc7-427d-9363-322238d1eb35.png)

This will assit with #275 #306 and #309.
However #276 will need to be addressed first (specifically VV)

**Comment by ScorelessPine** [comment]
I was going to create a new issue for this, however this issue seems to address many of the suggestions I would have made. However I would like to add, I think that Character conditional effects should also be added to this list, but _before_ the calculations are made, rather than after. All of these effects are accessible via the other tabs, however congregating them together in the build window before build calculation makes these effects more accessible and understandable. Certain effects like Hu Tao or Ayaka's skill elemental infusions, or Itto and Xiao's burst elemental infusions should be more accessible prior to build calculations, in my opinion.

**Comment by frzyc** [comment]
I don't really want to have too much UI bloat in optimize tab, not to mention, changing a conditional will have to re-calculate all the builds results, which is laggy. Go to the overview/talent/teambuff to change conditionals.
