### ISSUE TITLE
Allow roll value total and filtering on character equipment page

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#317]
![image](https://user-images.githubusercontent.com/101696552/165000337-3f34cdde-2b14-4b3f-9230-b7258c4b047a.png)

This could tie into #311 for comparisons against theory crafted builds and their roll values.

**Comment by StainAE86** [comment]
![image](https://user-images.githubusercontent.com/101696552/165239934-682ffe5b-9609-43e6-b747-ab2befe3efe8.png)
![image](https://user-images.githubusercontent.com/101696552/165239973-fef849fc-24f7-44b1-87c0-f67a162da376.png)

It would be nice to be able sort the character list by this as well. so you can see your most to least invested characters by your own metric.

**Comment by nguyentvan7** [comment]
I feel like this could get a little confusing. For example, if I set my Ayaka to only calculate RV based on atk, cd, cr. Then suddenly, a ton of other characters will be sorted above her, since they have the default RV filters where everything is considered. Or maybe that is expected by the user, not sure

**Comment by StainAE86** [comment]
> I feel like this could get a little confusing. For example, if I set my Ayaka to only calculate RV based on atk, cd, cr. Then suddenly, a ton of other characters will be sorted above her, since they have the default RV filters where everything is considered. Or maybe that is expected by the user, not sure Or we could default all characters to have no roll value enabled, then they have to configure each one in order to get a value displayed

Thats how I'd expect it to work - if you haven't configured a total Roll Value filter for a character they would just default to being excluded from the RV sorting and sit at the bottom of the list. Probably just defaulting to whatever the 'normal' sort order is? Alphabetical?

**Comment by StainAE86** [comment]
Adding onto this. The colour "scale" for the combined total RV would have to change slightly.
As it would essentially be impossible to achieve 4500% RV. And currently anything 540% or under (2700% combined) is grey indicating a "bad" or a low value build. This just isn't the case when it comes to looking at the build as a total.

My suggestion would be:

0-2000% = grey (+0 colour)
2000-2500 = dark green (+4 colour) 
2500-3000 = green (+8 colour)
3000-3500 = light green (+12 colour)
3500-4000 = blue (+16 colour)
4000-4500 = pink (+20 colour)

**Comment by StainAE86** [comment]
Another idea for this:
Instead of having the "Total RV" (might need a better name?) customizable by the user.
Have it calculate from the Optimization Target. This way the only substats used in the Total RV calculation are those directly contributing to the Optimization Target formula.

**This method has 2 major floors currently:**

1. How do you calculate the value of Energy Recharge when it doesn't contribute directly to DMG (like it does for Raiden or Emblem users)?
- This could be solved by including any stats the user has selected in the Build Constraints.
_EG: On Beidou the user has set 150% ER min - so now ER appears in "Total RV" since it is contributing directly to the build result._

2. How you do account for incidental scaling on other talents/abilities from other substats?
_EG: Optimizing for Yae's Burst would devalue all of her EM substats. But this is still valuable for her Skill._
- This is solved by _M U L T I - T A R G E T  OpTiMiZaTiOn_

**Comment by frzyc** [comment]
Im not opposed to streamlining RV into more aspect of the site, especially getting it in a more holistic view for character. However, I dont believe we should add it as a sorting metric, both since this will complicate existing sorting logic, but also are hard to configure (per character? global? global with character override?). I would not mind adding it into the equipment tab to begin with. I really dont think its a good idea to add it to the charactercard, since the minimized artifacts in the charactercard doesnt show substats, much less RV, so having a total RV seems a tad disjointed.
