### ISSUE TITLE
Double ties when sorting characters performs differently on different browsers

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#352]
Different browsers can implement .sort() differently, which means when there are ties that GO does not break, they will be broken by the browser. This means that character list can be sorted differently between browsers, even with the same settings. We should update the sorting code to fully resolve tiebreaks, probably by sorting by name as a last resort, since those are guaranteed unique.

**Comment by frzyc** [comment]
We have 2ndary tie breakers, but there are cases where both layers can produce the "same" result, which can be sorted differently in different browsers with different sort(). However, this doesn't make any of the implementations wrong. Even if the order is different, it is very localized. I hesitate to implement the sorting by name, since I am deliberating removing sorting by name altogether, since we can only sort by the "english" name, and we sort by the "long" name of characters (kokomi is under S, instead of K like people would expect). Sorting by name would be effectively useless on other languages.

**Comment by nguyentvan7** [comment]
I see no reason to remove sort by name. It's the only "consistent" sort, in that no matter my team's stats, I know that Zhongli will be last, Yunjin next to him, etc
