### ISSUE TITLE
Allow the artifact location filter to be a multi-select

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#424]
![image](https://user-images.githubusercontent.com/36019388/171476479-394a1c43-613a-4e14-8d02-55bb62c2a961.png)

**Comment by frzyc** [comment]
To retain the "Inventory" filter, probably need to make a "location multi autocomplete", as well as "in inventory" toggle

**Comment by frzyc** [comment]
Also, need to also add a toggle to select "all artifacts equipped on all characters" which will disable this autocomplete
<img width="512" alt="image" src="https://user-images.githubusercontent.com/1754901/213807412-649980b7-7aed-4163-bda0-009c653c9ab0.png">

**Comment by nguyentvan7** [comment]
Doesn't it make more sense for those to stay inside of the autocomplete itself? They are still locations technically

**Comment by frzyc** [comment]
"Equipped artifacts" conflict with location multi select, since it means "all equipped artifacts" whereas locaiton multiselect is "artifacts equipped on these characters"

Artifact in inventory should be default on, but location multi select is default off.

Both of these buttons conflict with the muilti-selection
