### ISSUE TITLE
Artifact Upgrade Probability (tooflesswulf)

### ISSUE THREAD

**Issue by tooflesswulf** [frzyc/genshin-optimizer#430]
Mostly a reminder to look at my work (https://github.com/tooflesswulf/genshin-optimizer/tree/master-with-wasm). The work mathematically models the random process of artifact upgrades, and offers a way to sort artifacts by the probability that the upgraded artifact improves a single build.

A technical report of the analysis and justification of the method are below. I've rewritten the mess of a paper from earlier to be specific to this work; should be a lot more readable now.

[GenshinOptimizer_UpgradePriority_TechnicalReport.pdf](https://github.com/frzyc/genshin-optimizer/files/8839459/GenshinOptimizer_UpgradePriority_TechnicalReport.pdf)

**Comment by StainAE86** [comment]
Linking the test version of this branch: https://tooflesswulf.github.io/genshin-optimizer/#/UpgradeOpt

It's currently very functional. And I do like the graph for visuallizing the upgrade probabilty.
However some thoughts when adding it to the main site would be:
- Clean up of the UI for filtering options
- Ability to set a minimum upgrade probability to reduce the amount of results.
eg: only show me results that have more than a 1% dmg increase
- And where to actually implement it:
on the optimize tab since it shares the opt target etc?
another tab on the character page? if you change the opt target/filtering on the 'upgrade' tab, will it also change those on the optimization tab?
somewhere in the artifact page? if so how do you link that back to a particular character?
or on its own page all together?

But I think the biggest one would be:
- The ability to find an entire new build based on the probability of another artifact being levelled, rather than just finding a new aritfact thats better for that single slot in the current build.
