### ISSUE TITLE
"Current number of substat rolles(10) + Rolls remaining from level up (0) is greater than the total possible roll of this artifact (9)"

### ISSUE THREAD

**Issue by Fraulk** [frzyc/genshin-optimizer#48]
i have an artifact with HP 29,2% and the optimizer thinks that it rolls 6 times, and the total amount seems to be too high because of this.
i'm not sure if it's the optimizer that don't detect it right, or maybe it's a bug from the game
or maybe i'm just dumb and there's something i didn't understood
![image](https://user-images.githubusercontent.com/25487503/113477097-fb220400-947f-11eb-9626-e9e99e834747.png)
![image](https://user-images.githubusercontent.com/25487503/113477121-273d8500-9480-11eb-8c1f-17816cb4e4de.png)

**Comment by frzyc** [comment]
The issue is genshin rounding. right now the number for the highest HP% roll on observable artifact is 5.8(rounded). however, the actually number is 5.82999.... which means that your roll is 29.15 -> 29.2. 
its an extreme cornercase, but it does happen, simply because we are using rounded values.
we are going to migrate to datamined data, but it will take some time. [https://trello.com/c/1X0Yk7jG/98-use-accurate-substate-roll-data-from-datamined-data](url)
for now, change your number to 29.1 or 29 and it should detect 5 rolls.
