### ISSUE TITLE
Bug: Changing a build constraint to another option creates a new line rather than swapping the selection

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#483]
![CPT2207091512-808x391](https://user-images.githubusercontent.com/101696552/178092589-b04cd7d8-f7a9-4c48-9472-57b2f162d5f2.gif)

**Comment by frzyc** [comment]
@nguyentvan7 does #479 resolve this issue?

**Comment by nguyentvan7** [comment]
Nope, looks like this is caused by the recent change in 8.8.9 to fix not being able to delete min filters.
On changing the stat, we call `close()`, followed by `setFilter()`

`close()` will delete the property from `statFilters`
![image](https://user-images.githubusercontent.com/36019388/178113911-e3dd1b65-4ea8-41ce-a3e0-9e95302d94fb.png)
But it now does so by deleting from a copy of `statFilters` (this is the change from 8.8.9).

Then we call `setFilter()`
![image](https://user-images.githubusercontent.com/36019388/178113961-356198d0-88de-4ead-b553-34e3d3b26920.png)
which will set the stat filters based on `statFilters`, which has still not been changed by the earlier `setStatFilters` call.
This wasn't an issue before 8.8.9 because we were directly deleting from `statFilters`.
