### ISSUE TITLE
Suggestion: Limit stats to 2 decimal places

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#513]
To help remove confusion for situations like this.

6.37 not 6,370

![image](https://user-images.githubusercontent.com/101696552/181753274-f04816b2-485c-436f-93f7-4727ab71542a.png)

**Comment by frzyc** [comment]
We have a dynamic rounding system, so the bigger the number, the less decimal is shown. 

This looks like a reading comprehension problem, since we do not use thousand separators on the site...

**Comment by balthanon** [comment]
I was going to post something like this except recommend rounding to a whole number in most cases honestly.  And I will say... while it is definitely a reading comprehension issue, it's because it is easy to miss the decimal.  I've made a similar error in the past myself and when I was introducing my sister to the site today, she made the same exact error, thinking that it was saying something like 2040 extra instead of 2.040.  

If you're glancing at a page full of numbers, it's pretty for your eyes to skim over a decimal point or ignore it when you're comparing a bunch of numbers in the thousands and then one that happens to come in at 6 or negative 6 with several mostly meaningless decimals after them.  If we're talking about a difference of .1 to .9, we're really talking about the same value as far as Genshin is concerned as well.  Maybe not at the code level, but from a functional standpoint and comparing it to what you see in the game on your character and artifacts.

So to that extent, I would say it is a UI issue addressed at minimizing the effort required to take in the information the site is spitting out quickly and easily (i.e. the effort for reading comprehension :))-- is it critical?  Absolutely not.  But very few of the numbers that Genshin Optimizer spits out really benefit from decimal points either when you're reviewing the data.  So you lose a little granularity while making it easier to make quick comparisons.   (That might not be the case when you're debugging, of course.)
