### ISSUE TITLE
Store Traveler talent levels per Element selection

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#593]
The same goes for Constellations - but is less of an issue since everyone eventually has C6 of every Traveler version.
But because you have to level the Traveler's talents for each elemental version it's unlikely everyone has evenly invested into Anemo/Geo/Electro and Dendro.

**Comment by littlef0x** [comment]
Agree.
Also, I'd like to suggest to store each traveler's whole profile separately since builds for them are quite different. For example, for Geo traveler, I'll use Geo dmg goblet+PJC+4 Geo team. And that doesn't fit traveler of other elements.
So the only thing that share between different travelers is the level. My suggestion is that the traveler should still appear as a single character. But all the contents are separated except the level when you switch the element.
