### ISSUE TITLE
Artifacts with three 5.8 ATK%/HP% substat rolls have an invalid RV

### ISSUE THREAD

**Issue by nguyentvan7** [frzyc/genshin-optimizer#674]
![image](https://user-images.githubusercontent.com/36019388/194154852-bfb7aa0d-5b68-45e2-a63b-c08f2e608d62.png)

**Comment by lantua** [comment]
Due to rounding error, the RV is `300.00000000000006`, but `PercengBadge` only selects the colour for up to `300%` for that component (via the `max` field). There are a few possible solutions, including

- Add tolerant for the `max` checking, so small out-of-bound values would remain valid,
- Remove the `max` checking in `PercentBadge,` and clamp the colour should it go out of bounds. Most usage of `PercantBadge` are already accompanied by value validation, so the effect should be minimal, and
- Round `efficiency` (`300.00000000000006`) to within bound when computing the artifact cache.

**Comment by frzyc** [comment]
Gonna let @lantua take the reins on this because my solution is probably not up to his standards
![image](https://user-images.githubusercontent.com/1754901/196001420-0b8cfda2-53da-41ef-b2f2-41b3026527b7.png)
