### ISSUE TITLE
Artifact Set Configuration

### ISSUE THREAD

**Issue by randoomdude** [frzyc/genshin-optimizer#700]
The last time I used GO, you had this option in the optimizer to set a certain artifact set if you wanted, so like an Anemo character could set Viridescent and it would make sure to generate a set that at least had a set of those artifacts and it was very useful, but now you have to manually set Allowed/Excluded and it makes it so you can't just pick 1 set you want to include, but have to manually exlucde all the ones you want, and then the ones you want, it takes a lot more time and what's more I don't always know what to exclude cause I only know what I want to include,  and overall I just preferred the previous way of doing it a lot more, any option to at least have that option back?
![image](https://user-images.githubusercontent.com/6027132/196289880-9a5d231d-bc51-48a1-b580-e13575962098.png)

**Comment by StainAE86** [comment]
It's only 4 clicks to exclude everything and then 1 click to include the single set you want (in the case of VV)

The "force set" feature won't come back because it was more harmful than good. Plus much more limiting.
As the game has evolved with new characters etc there are more cases where a character can you multiple different sets to very similar results. But also have sets that on the surface look like they could be good (like Shimenewaa for example) that need to be excluded.

This is why the feature was expanded on to allow granularity in exact sets and 2pc/4pc that can be included and excluded in the calculation.

**Comment by randoomdude** [comment]
Why does it take so long though, it use to be quicker if you refined the search, now it takes longer for searching less?
![2022-10-27 15 58 56](https://user-images.githubusercontent.com/6027132/198413565-a550bb37-a137-46d8-943b-99be51bbcd30.png)
![2022-10-18 21 38 34](https://user-images.githubusercontent.com/6027132/198413579-d013e19b-9127-47ee-a6fa-852671260394.png)

**Comment by StainAE86** [comment]
You've left "3 rainbow" enabled. This essentially turns off all "pruning" functions so every single possible build within those constraints needs to be checked so it takes longer than leaving all options turned on and the objectively worse builds are pruned out.
