### ISSUE TITLE
Add Graph Axis labels

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#713]
Already suggested in #502 however should be bumped to the top of the list.
With the introduction of Graph Opt. Target vs. Opt. Target it's difficult to quickly read the graph and tell which axis is which:

![image](https://user-images.githubusercontent.com/101696552/197728665-ad9d4259-dba2-4bf8-94ef-495078ed62f8.png)

Maybe put the name of the character within the Graph as well since its likely people will start sharing their Graph results:

![image](https://user-images.githubusercontent.com/101696552/197731588-32744c3f-e6c1-4435-b64a-4e84a1232fbd.png)

**Comment by nguyentvan7** [comment]
I tried doing this, but seems there is a limitation in the recharts API, though I guess we could just superimpose the labels on top of the chart ourself.

Recharts labels only render strings or numbers, and the labels can sometimes be React components due to translation stuff. Technically they are supposed to support component labels, but it seems bugged 

https://github.com/recharts/recharts/issues/1789
