### ISSUE TITLE
Separate Bountiful Core from Bloom DMG

### ISSUE THREAD

**Issue by StainAE86** [frzyc/genshin-optimizer#720]
Currently on Nilou (or her team) when the "Golden Chalice's Bounty" conditional is active the Bloom DMG gets the A4 Bonus added to it to convert it to the Bountiful Core damage.

However this causes two issues;

1) The wording "Bountiful Core" does not appear as a Optimization Target which can be confusing to users
2) Nilou and her team have the ability to create normal Bloom seeds / do normal Bloom DMG before Nilou activates her skill and after it expires. This makes creating custom Multi-Targets more challenging

This could possibly spark more conversation on how conditionals are handled within Multi-Targets?
As currently the only way to deal with such situations is to disable the conditional and add the stats manually

**Comment by nguyentvan7** [comment]
I've thought about this issue a lot, and I just feel like it is not worth adding this. Maybe if it was more common that people mixed regular blooms with bountiful core bloom in a nilou comp, but it is not common due to > 100% uptime.

And like you mentioned, this behaves exactly like other conditionals, such as Shenhe quills or something, where the buff needs to be manually added by the user when multi-target optimizing. And Shenhe quills are significantly more likely to be intermixed in an opt target. Feel free to re-open as a general issue to "add conditional support in multi-target" (Datanode 2.0 when lantua)
