### ISSUE TITLE
Nahida ascension 4 talent crit rate bonus is not considered for calculations

### ISSUE THREAD

**Issue by anuchin** [frzyc/genshin-optimizer#780]

**Comment by Sinesthesia** [comment]
![image](https://user-images.githubusercontent.com/23565001/202958178-cb4f6e2b-0e2c-4173-8ff8-bb312d0205b8.png)

**Comment by StainAE86** [comment]
As Sin as shown above it is included in the calculations. Here is another view:

![image](https://user-images.githubusercontent.com/101696552/202965398-a76a4b74-5dc6-46f2-906d-dddf1b39296c.png)

50.5% + 24% = 74.5%

It only appears in the tooltip when you are on "Avg. DMG" since if you are looking at Non-Crit or Crit DMG numbers obviously Crit Rate doesn't factor into the calculation.

Also if you are confused and think it should appear on the left as a global Crit Rate figure - it does not. Just like in-game.
Since the Crit Rate bonus is _ONLY_ for the Tri-Karma Purification DMG, not all sources of Nahida's damage.

**Comment by anuchin** [comment]
thanks for the info!!!
