### ISSUE TITLE
Slow Optimization with 5-Rainbow Disabled

### ISSUE THREAD

**Issue by lokyst** [frzyc/genshin-optimizer#831]
The total time to solve with 5-Rainbow disabled is considerably longer than with it enabled.

In the example below with 5-Rainbow disabled, it has taken 76 seconds to process 569,653 builds. This averages to about 7495 builds per second.

5-Rainbow Disabled
![image](https://user-images.githubusercontent.com/6118775/208303578-51e350cc-c399-4a46-9838-26092689efa6.png)

Compare this with 5-Rainbow enabled, where the summary says  it took 7 seconds to process 7,948,044 builds. This averages to about  1,135,434 builds per second.

5-Rainbow Enabled
![image](https://user-images.githubusercontent.com/6118775/208303673-501565d3-a6d4-4a8c-93ce-bdc2a75fd4a8.png)

How to replicate:
Microsoft Edge - Version 108.0.1462.46 (Official build) (64-bit)
[JSON DB](https://github.com/frzyc/genshin-optimizer/files/10254000/Test_broken__2022-12-18_14-26-03.zip)
No artifact conditional effects enabled.
Multi-Target Config if required:
```
{"name":"E3N4CQ","targets":[{"weight":1,"path":["skill","dmg"],"hitMode":"avgHit","bonusStats":{}},{"weight":1,"path":["normal","0"],"hitMode":"avgHit","bonusStats":{}},{"weight":1,"path":["normal","1"],"hitMode":"avgHit","bonusStats":{}},{"weight":2,"path":["normal","2"],"hitMode":"avgHit","bonusStats":{}},{"weight":4,"path":["charged","dmg"],"hitMode":"avgHit","bonusStats":{}},{"weight":5,"path":["burst","dmg"],"hitMode":"avgHit","bonusStats":{}}]}
```
Optimizer Settings
![image](https://user-images.githubusercontent.com/6118775/208303771-3d7bc97b-1e5f-415f-9487-2c18a192dd70.png)
Team Buffs
![image](https://user-images.githubusercontent.com/6118775/208303901-3a9da891-1081-407c-b53b-763ed0dc781e.png)
Talents
![image](https://user-images.githubusercontent.com/6118775/208303953-8466781b-0195-48f5-b802-dcdaeb65a8e7.png)

**Comment by D1firehail** [comment]
I don't know the exact details, but it's specifically mentioned in the video on the set filter https://www.youtube.com/watch?v=Ate5O2UuRJE&t=24s

**Comment by nguyentvan7** [comment]
There is also an ongoing optimization bug #802 that is probably affecting this as well

**Comment by lokyst** [comment]
Balakin1 on Discord also seemed to think it might be related to an existing issue, probably #802. https://discord.com/channels/785153694478893126/785176548428087306/1053159438833426582

**Comment by StainAE86** [comment]
This is completely expected behavior when only turning off 5-rainbow (similar results would be had turning off 3-rainbow)

The issue is being exaggerated by the fact Wanderer is on the top of your priority list, you're allowing low level (+8) artifacts and you've got hundreds of partially levelled artifacts the Optimizer is now forced to check _every_ combination of to rule out if it's going to be a 5-rainbow build.

Like alluded to in the video and said in the discord - if you're going to turn off the rainbow options you MUST also change other 2/4-set options otherwise it will unintuitively be significantly slower.

If I turn off all other 2/4-sets that I know should never be used in the build generation and then limit the build page's use of levelled artifacts to +12 to +20 it's now giving the exact same result you would have received by waiting that 1+ min.
![image](https://user-images.githubusercontent.com/101696552/208315135-eb4c3448-fba4-44f0-b92c-abf498c5384c.png)

1.3 second build time.

**Comment by doxxx** [comment]
That's _three_ orders of magnitude slower, for _removing_ artifacts from the set to be evaluated. That's extremely counter-intuitive. Are you certain this isn't related to the Firefox performance issue?

**Comment by StainAE86** [comment]
> That's _three_ orders of magnitude slower, for _removing_ artifacts from the set to be evaluated. That's extremely counter-intuitive. Are you certain this isn't related to the Firefox performance issue?

The Firefox issue may also be slowing it down further but I don't believe so as 76sec isn't that bad for disallowing rainbow builds.

Because you aren't removing ANY artifacts from the pool. Every artifact can still be used as an off piece with the added check that it's not also going to be used with another off set piece. So disallowing rainbow settings actually increases the calculation workload.

**Comment by nguyentvan7** [comment]
Afaik most of all of the performance issues are mitigated if you clear your build list before you generate. So if the rainbow is still taking forever with a clear build list, it's just how rainbow pruning works

**Comment by lantua** [comment]
> Are you certain this isn't related to the Firefox performance issue?

If workaround doesn't help, yes.
