### ISSUE TITLE
Missing Character [Yun Jin]

### ISSUE THREAD

**Issue by Moeplays** [frzyc/genshin-optimizer#92]
thanks a bunch for the awesome tool! <3
I noticed that Yun Jin was missing from the characters list. I am new here so i am not sure if this is the right place to mention it.

p.s.: she is missing from the optimizer (manual add) but recognized by scanners, upon import it says 1 invalid character and shows her data.

**Comment by D1firehail** [comment]
Quote from the announcements channel in discord:

> **Version 2.4 Contents in GO**
Ever since version 2.0, MHY has released characters/weapons with kits that seem to defy the original design considerations of the Optimizer. Unfortunately, to design a hyper optimized system, GO is designed with a lot of assumptions to what "general" forms the formulas in Genshin will take. These assumptions have been feature crept to obsoletion. Weapons like Moonglow and Spindle, characters like Kujou Sara and Gurou, are no longer able to fit into the Optimizer ecosystem. As 2.4 has been released, we've seen MHY double down on these "incompatible" game mechanics, which makes implementing the new characters almost pointless. 
> 
> The good news is that we've been anticipating this feature creep, and we've designed a new system to accommodate the new changes. However, we will need a lot more time putting vision into code, and even more time migrating all the existing characters/artifact/weapons to the new system. I cannot promise any concrete ETAs, since such an undertaking can have many perilous setbacks, and quite a lot of unanticipated issues. There will be somewhat minimal updates to the implementation process of this system for the same reason, so the only thing you can do for now is to please keep in mind that we are presently working on a solution.
